### ISSUE TITLE
Identifiers starting with "def" cause errors

### ISSUE THREAD

**Issue by bovlb** [alexhagen/jdc#2]
```
import jdc
```

```
class foo:
    pass
```

```
%%add_to foo
def bar():
    defective = True
```

>   File "<string>", line 5
>     foo.bar = bar
>       ^
> IndentationError: expected an indented block

```
%%add_to foo
def baz():
    x = deference()
```

>   File "<string>", line 2
>     x =
>         ^
> SyntaxError: invalid syntax​
>

**Comment by alexhagen** [comment]
I've went ahead and solved this: now ``jdc`` splits the cell by "def " instead of just by "def".  If there are other problems popping up related to this, I'll have to write a regex to find function definitions.

Go ahead and update your ``jdc`` to 0.0.7 with

```bash

pip uninstall jdc
pip install --no-cache-dir jdc
```

The working code I used to test this was:

```python

import jdc
class dog(object):
    def __init__(self, name, noise):
        self.name = name
        self.noise = noise
        
        
rover = dog('Rover', 'ruff')
spot = dog('Spot', 'woof')

```

and then

```python
%%add_to dog
def bar():
    defective = True
```

**Comment by bovlb** [comment]
Looks good.  Thanks for the quick turnaround!
